### ISSUE TITLE
Support for variables when casting text

### ISSUE THREAD

**Issue by carlptr** [FrostedKiwi/pimatic-chromecast#2]
It would make the plugin much more flexible when variables could be used within the casted texts.

Here is for example my action text:
cast-text "$chromecast-meldung" in language "de" on chromecast-keller and send pushbullet message:"$chromecast-meldung" channel:"$pushbullet-monitor-channel"

The variable $chromecast-meldung is resolved by the pushbullet plugin, but not by the chromecast plugin. The pushbullet-plugin seems to use something like  @framework.variableManager.evaluateStringExpression for that but I'm not skilled enough to hack this by myself.

**Comment by FrostedKiwi** [comment]
Issue has been fixed in 1.2.2
